### ISSUE TITLE
Issue with Associating User Accounts- user portal

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/identity-apps#298]
Affected version:
wso2is: wso2is-5.10.0-alpha3-SNAPSHOT
Identity -app: 0.9.11-SNAPSHOT

**Describe the bug**
1. Initially, Log in with a user who has permission to view operations(e.g admin),
 and initiate a new user account association but that user has only the login permission.
2. switch between associated user account that user has only the login permission.
3. again switch to the initial user who has permission to view operations(e.g admin)
**Issue: the application does not display the "operations" in the left side but ser who has permission to view operations (e.g admin),**

Screenshots:
Initially, Log in with a user who has permission to view operations(e.g admin),
![image](https://user-images.githubusercontent.com/39120228/73003129-1bd9dd00-3e2b-11ea-8fa4-5e0f5e292b5e.png)

2. switch between associated user account that user has only the login permission.
![image](https://user-images.githubusercontent.com/39120228/73003252-50e62f80-3e2b-11ea-9290-3a66e66dd9c1.png)

3. switch to the initial user who has permission to view operations(e.g admin)
![image](https://user-images.githubusercontent.com/39120228/73003342-7f640a80-3e2b-11ea-97af-8e2ba8ce40f1.png)

**Comment by thivi** [comment]
This is because the API endpoint is returning only `intenal_login` and `openid` scopes following account switching even for an admin user. 

The request body
![image](https://user-images.githubusercontent.com/20745428/73054958-acf39700-3eb1-11ea-9b19-dd1cbede980c.png)

The response
![Screenshot 2020-01-24 at 13 55 52](https://user-images.githubusercontent.com/20745428/73054855-6f8f0980-3eb1-11ea-866e-72585ca1da13.png)

**Comment by thivi** [comment]
This issue has been resolved by this PR: https://github.com/wso2-extensions/identity-user-account-association/pull/34
Related issue: https://github.com/wso2/product-is/issues/7385

**Comment by thanujalk** [comment]
This is fixed.
